const string = () => ({ type: "string" });
const number = () => ({ type: "number" });
const integer = () => ({ type: "integer" });
const boolean = () => ({ type: "boolean" });

const commonProperties = {
  promotion_channel: string(),
  device: string(),
  region: string(),
  age_group: string(),
  gender: string(),
  user_type: string(),
  user_segment: string(),
  preferred_category: string(),
  campaign_id: string(),
  promotion_id: string(),
  promotion_run_id: string(),
  ad_experiment_id: string(),
  segment_id: string(),
  content_id: string(),
  content_option_id: string(),
  placement_id: string(),
  redirect_id: string(),
  target_url: string(),
  attribution_source: string(),
  attribution_placement_key: string(),
  attribution_page: string(),
  attribution_stored_at: string(),
  campaign_source: string(),
  campaign_medium: string(),
  campaign_name: string(),
  deal: string(),
};

const searchProperties = {
  destination_id: string(),
  check_in: string(),
  check_out: string(),
  adults: integer(),
  children: integer(),
  rooms: integer(),
};

const hotelProperties = {
  hotel_id: string(),
  hotel_name: string(),
  hotel_market: string(),
  hotel_city: string(),
  destination_id: string(),
  destination_name: string(),
  neighborhood: string(),
  hotel_star_rating: integer(),
  hotel_guest_rating: number(),
  property_type: string(),
  refundable: boolean(),
  pay_later: boolean(),
  price: number(),
};

const stayProperties = {
  checkin_date: string(),
  checkout_date: string(),
  adult_count: integer(),
  child_count: integer(),
};

function event(eventName, description, properties = {}, required = []) {
  return {
    eventName,
    description,
    propertiesSchema: {
      type: "object",
      properties: {
        ...commonProperties,
        ...properties,
      },
      required,
    },
  };
}

export const trackingPlanEvents = [
  event("page_view", "Browser route view", {
    route_group: string(),
  }),
  event(
    "promotion_impression",
    "Rendered advertisement impression",
    {
      slot_id: string(),
      placement_page: string(),
      viewport: string(),
      source_event_time: string(),
      source: string(),
    },
    [
      "campaign_id",
      "promotion_id",
      "promotion_run_id",
      "ad_experiment_id",
      "segment_id",
      "content_id",
      "content_option_id",
      "placement_id",
      "target_url",
      "slot_id",
      "placement_page",
      "viewport",
      "source_event_time",
      "source",
    ],
  ),
  event(
    "promotion_click",
    "Rendered advertisement click",
    {
      slot_id: string(),
      placement_page: string(),
      viewport: string(),
      source_event_time: string(),
      source: string(),
    },
    [
      "campaign_id",
      "promotion_id",
      "promotion_run_id",
      "ad_experiment_id",
      "segment_id",
      "content_id",
      "content_option_id",
      "placement_id",
      "target_url",
      "slot_id",
      "placement_page",
      "viewport",
      "source_event_time",
      "source",
    ],
  ),
  event("campaign_redirect_click", "Campaign redirect arrival", {
    landing_type: string(),
    landing_url: string(),
    landing_path: string(),
    previous_url: string(),
  }),
  event("campaign_landing", "Campaign landing arrival", {
    landing_type: string(),
    landing_url: string(),
    landing_path: string(),
    previous_url: string(),
  }),
  event(
    "hotel_search",
    "Hotel search submitted",
    {
      ...stayProperties,
      ...searchProperties,
      route_group: string(),
    },
    [
      "checkin_date",
      "checkout_date",
      "adult_count",
      "child_count",
      "destination_id",
      "check_in",
      "check_out",
      "adults",
      "children",
      "rooms",
      "route_group",
    ],
  ),
  event(
    "hotel_detail_view",
    "Hotel detail viewed",
    {
      ...hotelProperties,
      ...searchProperties,
      route_group: string(),
    },
    [
      "hotel_id",
      "hotel_market",
      "hotel_city",
      "hotel_name",
      "price",
      "destination_id",
      "check_in",
      "check_out",
      "adults",
      "children",
      "rooms",
      "route_group",
    ],
  ),
  event(
    "hotel_click",
    "Hotel result selected",
    {
      ...hotelProperties,
      ...stayProperties,
      ...searchProperties,
      free_cancellation: boolean(),
      currency: string(),
      route_group: string(),
    },
    [
      "hotel_id",
      "hotel_market",
      "hotel_city",
      "hotel_name",
      "checkin_date",
      "checkout_date",
      "adult_count",
      "child_count",
      "free_cancellation",
      "price",
      "currency",
      "route_group",
    ],
  ),
  event(
    "booking_start",
    "Checkout started",
    {
      ...hotelProperties,
      ...stayProperties,
      ...searchProperties,
      room_type: string(),
      breakfast_included: boolean(),
      free_cancellation: boolean(),
      revenue: number(),
      currency: string(),
      room_id: string(),
      room_name: string(),
      room_capacity: integer(),
      room_refundable: boolean(),
      nights: integer(),
      booking_value: number(),
      route_group: string(),
    },
    [
      "hotel_id",
      "room_type",
      "checkin_date",
      "checkout_date",
      "adult_count",
      "child_count",
      "breakfast_included",
      "free_cancellation",
      "price",
      "revenue",
      "currency",
      "room_id",
      "nights",
      "booking_value",
      "route_group",
    ],
  ),
  event(
    "booking_complete",
    "Booking completed",
    {
      ...stayProperties,
      booking_id: string(),
      room_type: string(),
      revenue: number(),
      currency: string(),
      hotel_id: string(),
      hotel_name: string(),
      room_id: string(),
      room_name: string(),
      check_in: string(),
      check_out: string(),
      adults: integer(),
      children: integer(),
      rooms: integer(),
      payment_option: string(),
      booking_value: number(),
      inventory_status: string(),
      is_booking: integer(),
      route_group: string(),
    },
    [
      "booking_id",
      "hotel_id",
      "room_id",
      "checkin_date",
      "checkout_date",
      "adult_count",
      "child_count",
      "revenue",
      "currency",
      "booking_value",
      "inventory_status",
      "is_booking",
      "route_group",
    ],
  ),
  event(
    "booking_cancel",
    "Booking cancelled",
    {
      ...stayProperties,
      booking_id: string(),
      room_type: string(),
      revenue: number(),
      currency: string(),
      hotel_id: string(),
      hotel_name: string(),
      room_id: string(),
      room_name: string(),
      check_in: string(),
      check_out: string(),
      adults: integer(),
      children: integer(),
      rooms: integer(),
      cancellation_reason: string(),
      cancelled_at: string(),
      route_group: string(),
    },
    [
      "booking_id",
      "hotel_id",
      "room_id",
      "checkin_date",
      "checkout_date",
      "adult_count",
      "child_count",
      "revenue",
      "currency",
      "cancellation_reason",
      "cancelled_at",
      "route_group",
    ],
  ),
  event(
    "schema_validation_probe",
    "Manual and DOM typed JSON validation probe",
    {
      sample_id: string(),
      amount: number(),
      quantity: integer(),
      active: boolean(),
      tags: {
        type: "array",
        items: string(),
      },
      item: {
        type: "object",
        properties: {
          sku: string(),
          count: integer(),
        },
        required: ["sku", "count"],
      },
    },
    ["sample_id", "amount", "quantity", "active", "tags", "item"],
  ),
];
